WarbandComms.CareerIdToLine = {
	[20] = GameData.CareerLine.IRON_BREAKER,
	[100] = GameData.CareerLine.SWORDMASTER,
	[64] = GameData.CareerLine.CHOSEN,
	[24] = GameData.CareerLine.BLACK_ORC,
	[60] = GameData.CareerLine.WITCH_HUNTER,
	[102] = GameData.CareerLine.WHITE_LION or GameData.CareerLine.SEER,
	[65] = GameData.CareerLine.MARAUDER or GameData.CareerLine.WARRIOR,
	[105] = GameData.CareerLine.WITCH_ELF or GameData.CareerLine.ASSASSIN,
	[62] = GameData.CareerLine.BRIGHT_WIZARD,
	[67] = GameData.CareerLine.MAGUS,
	[107] = GameData.CareerLine.SORCERER,
	[23] = GameData.CareerLine.ENGINEER,
	[101] = GameData.CareerLine.SHADOW_WARRIOR,
	[27] = GameData.CareerLine.SQUIG_HERDER,
	[63] = GameData.CareerLine.WARRIOR_PRIEST,
	[106] = GameData.CareerLine.DISCIPLE or GameData.CareerLine.BLOOD_PRIEST,
	[103] = GameData.CareerLine.ARCHMAGE,
	[26] = GameData.CareerLine.SHAMAN,
	[22] = GameData.CareerLine.RUNE_PRIEST,
	[66] = GameData.CareerLine.ZEALOT,
	[104] = GameData.CareerLine.BLACKGUARD or GameData.CareerLine.SHADE,
	[61] = GameData.CareerLine.KNIGHT,
	[25] = GameData.CareerLine.CHOPPA,
	[21] = GameData.CareerLine.SLAYER,
};

WarbandComms.CAREERS = {
	[0] = {["type"] = "npc", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20187>"},
	[GameData.CareerLine.ENGINEER] = {["type"] = "rdps", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20187>"},
	[GameData.CareerLine.BRIGHT_WIZARD] = {["type"] = "rdps", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20183>"},
	[GameData.CareerLine.SORCERER] = {["type"] = "rdps", ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20196>"},
	[GameData.CareerLine.SQUIG_HERDER] = {["type"] = "rdps", ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20197>"},
	[GameData.CareerLine.MAGUS] = {["type"] = "rdps", ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20191>"},
	[GameData.CareerLine.SHADOW_WARRIOR] = {["type"] = "rdps", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20194>"},
	[GameData.CareerLine.WITCH_ELF] = {["type"] = "mdps", ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20201>"},
	[GameData.CareerLine.WHITE_LION] = {["type"] = "mdps", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20200>"},
	[GameData.CareerLine.SLAYER] = {["type"] = "mdps", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20188>"},
	[GameData.CareerLine.WITCH_HUNTER] = {["type"] = "mdps", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20202>"},
	[GameData.CareerLine.CHOPPA] = {["type"] = "mdps", ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20184>"},
	[GameData.CareerLine.MARAUDER] = {["type"] = "mdps", ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20192>"},
	[GameData.CareerLine.IRON_BREAKER] = {["type"] = "tank",  ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20189>"},
	[GameData.CareerLine.CHOSEN] = {["type"] = "tank",  ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20185>"},
	[GameData.CareerLine.BLACK_ORC] = {["type"] = "tank",  ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20182>"},
	[GameData.CareerLine.KNIGHT] = {["type"] = "tank",  ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20190>"},
	[GameData.CareerLine.SWORDMASTER] = {["type"] = "tank",  ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20198>"},
	[GameData.CareerLine.BLACKGUARD] = {["type"] = "tank",  ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20181>"},
	[GameData.CareerLine.ZEALOT] = {["type"] = "healer", ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20203>"},
	[GameData.CareerLine.WARRIOR_PRIEST] = {["type"] = "healer", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20199>"},
	[GameData.CareerLine.RUNE_PRIEST] = {["type"] = "healer", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20193>"},
	[GameData.CareerLine.ARCHMAGE] = {["type"] = "healer", ["faction"] = GameData.Realm.ORDER, ["icon"] = "<icon20180>"},
	[GameData.CareerLine.SHAMAN] = {["type"] = "healer", ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20195>"},
	[GameData.CareerLine.DISCIPLE] = {["type"] = "healer", ["faction"] = GameData.Realm.DESTRUCTION, ["icon"] = "<icon20186>"},
}